import { Movie, SortField } from "./types";

export const MOVIES_STORAGE_KEY = "movies";

export const MOVIES: Movie[] = [
  {
    id: "1",
    title: "Inception",
    director: "Christopher Nolan",
    year: 2010,
    rating: 9,
    image: "/imgs/cardbg.webp",
    genres: ["sci-fi", "action", "thriller"],
    mainActors: "Leonardo DiCaprio, Joseph Gordon-Levitt",
    description:
      "A skilled thief who steals secrets through dream-sharing technology is given a chance to erase his past crimes.",
  },
  {
    id: "2",
    title: "Morphine",
    director: "John Doe",
    year: 2008,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["noir", "drama", "horror"],
    mainActors: "Leonid Bichevin, Ingeborga Dapkunaite",
    description:
      "A young doctor in 1917 struggles with addiction and the harsh realities of a collapsing society.",
  },
  {
    id: "3",
    title: "Akira",
    director: "Katsuhiro Otomo",
    year: 1988,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["animation", "action", "horror"],
    mainActors: "Mitsuo Iwata, Nozomu Sasaki",
    description:
      "A biker gang member gains dangerous psychic powers in a dystopian Neo-Tokyo.",
  },
  {
    id: "4",
    title: "The Grand Budapest Hotel",
    director: "Wes Anderson",
    year: 2014,
    rating: 8,
    image: "/imgs/cardbg.webp",
    genres: ["comedy", "crime"],
    mainActors: "Ralph Fiennes, Tony Revolori",
    description:
      "A hotel concierge becomes entangled in a murder mystery and a stolen painting.",
  },
  {
    id: "5",
    title: "Interstellar",
    director: "Christopher Nolan",
    year: 2014,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["sci-fi", "drama"],
    mainActors: "Matthew McConaughey, Anne Hathaway",
    description:
      "A team travels through a wormhole to find a new home for humanity.",
  },
  {
    id: "6",
    title: "Parasite",
    director: "Bong Joon-ho",
    year: 2019,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["drama", "thriller"],
    mainActors: "Song Kang-ho, Lee Sun-kyun",
    description: "A poor family schemes to infiltrate a wealthy household.",
  },
  {
    id: "7",
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    rating: 9.0,
    image: "/imgs/cardbg.webp",
    genres: ["action", "crime", "drama"],
    mainActors: "Christian Bale, Heath Ledger",
    description:
      "Batman faces the Joker, a criminal mastermind spreading chaos in Gotham.",
  },
  {
    id: "8",
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    rating: 9,
    image: "/imgs/cardbg.webp",
    genres: ["crime", "drama"],
    mainActors: "John Travolta, Samuel L. Jackson",
    description:
      "Interconnected stories of crime and redemption unfold in Los Angeles.",
  },
  {
    id: "9",
    title: "Spirited Away",
    director: "Hayao Miyazaki",
    year: 2001,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["animation", "fantasy"],
    mainActors: "Rumi Hiiragi, Miyu Irino",
    description: "A girl enters a magical world and must save her parents.",
  },
  {
    id: "10",
    title: "The Matrix",
    director: "The Wachowskis",
    year: 1999,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["sci-fi", "action"],
    mainActors: "Keanu Reeves, Laurence Fishburne",
    description:
      "A hacker discovers reality is a simulation and joins a rebellion.",
  },
  {
    id: "11",
    title: "Fight Club",
    director: "David Fincher",
    year: 1999,
    rating: 9,
    image: "/imgs/cardbg.webp",
    genres: ["drama"],
    mainActors: "Brad Pitt, Edward Norton",
    description: "An insomniac office worker forms an underground fight club.",
  },
  {
    id: "12",
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    rating: 9.5,
    image: "/imgs/cardbg.webp",
    genres: ["crime", "drama"],
    mainActors: "Marlon Brando, Al Pacino",
    description:
      "The aging patriarch of a crime family transfers control to his son.",
  },
  {
    id: "13",
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    rating: 3,
    image: "/imgs/cardbg.webp",
    genres: ["drama", "romantic"],
    mainActors: "Tom Hanks, Robin Wright",
    description:
      "A simple man witnesses and influences key moments in history.",
  },
  {
    id: "14",
    title: "Gladiator",
    director: "Ridley Scott",
    year: 2000,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["action", "historical", "drama"],
    mainActors: "Russell Crowe, Joaquin Phoenix",
    description: "A Roman general seeks revenge after betrayal.",
  },
  {
    id: "15",
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    rating: 4.5,
    image: "/imgs/cardbg.webp",
    genres: ["drama"],
    mainActors: "Tim Robbins, Morgan Freeman",
    description: "A banker forms a friendship while serving a life sentence.",
  },
  {
    id: "16",
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    year: 1991,
    rating: 1.5,
    image: "/imgs/cardbg.webp",
    genres: ["thriller", "crime"],
    mainActors: "Jodie Foster, Anthony Hopkins",
    description: "An FBI trainee seeks help from a cannibalistic killer.",
  },
  {
    id: "17",
    title: "La La Land",
    director: "Damien Chazelle",
    year: 2016,
    rating: 8.0,
    image: "/imgs/cardbg.webp",
    genres: ["romantic", "musical"],
    mainActors: "Ryan Gosling, Emma Stone",
    description:
      "Two artists fall in love while chasing dreams in Los Angeles.",
  },
  {
    id: "18",
    title: "The Good, the Bad and the Ugly",
    director: "Sergio Leone",
    year: 1966,
    rating: 5,
    image: "/imgs/cardbg.webp",
    genres: ["western"],
    mainActors: "Clint Eastwood, Eli Wallach",
    description:
      "Three gunslingers search for hidden gold during the Civil War.",
  },
  {
    id: "19",
    title: "Se7en",
    director: "David Fincher",
    year: 1995,
    rating: 8.5,
    image: "/imgs/cardbg.webp",
    genres: ["crime", "mystery", "thriller"],
    mainActors: "Brad Pitt, Morgan Freeman",
    description:
      "Detectives hunt a serial killer who uses the seven deadly sins.",
  },
  {
    id: "20",
    title: "Into the Wild",
    director: "Sean Penn",
    year: 2007,
    rating: 4.0,
    image: "/imgs/cardbg.webp",
    genres: ["drama", "advanture"],
    mainActors: "Emile Hirsch, Marcia Gay Harden",
    description:
      "A young man abandons society to live in the Alaskan wilderness.",
  },
];

export const sortFields: SortField[] = ["rating", "title", "year"];
