import "./globals.css";

import type { Metadata } from "next";
import { Alata, Anonymous_Pro } from "next/font/google";

const anonymousPro = Anonymous_Pro({
  weight: ["400", "700"],
  variable: "--font-anonymous-pro",
});

const alata = Alata({
  weight: ["400"],
  variable: "--font-alata",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anonymousPro.variable} ${alata.variable}`}>
        {children}
      </body>
    </html>
  );
}
